channels:
- conda-forge
dependencies:
- pyiron_atomistics=0.2.13
- pyiron_gpl=0.0.3
- pyiron_continuum=0.0.1
- lammps=2021.02.10
- sqsgenerator=0.0.5
- damask=3.0.0
- vtk=9.0.1
- itkwidgets=0.32.0
- pyvista=0.31.0
- h5py=3.2.1
- nglview=3.0.1
- seaborn=0.11.1
- papermill
