channels:
- conda-forge
dependencies:
- pyiron=0.4.0
- lammps=2020.12.24
- sqsgenerator=0.0.5
- damask=3.0.0=py37h9964bdb_8
- vtk=9.0.1
- itkwidgets=0.32.0
- pyvista=0.27.4
- h5py=3.1.0
- nglview=2.7.7
- seaborn=0.11.1
